### ISSUE TITLE
[ChannelTabs] Tabs don't update. 

### ISSUE THREAD

**Issue by EnoralTheOutCast** [samfundev/BetterDiscordStuff#12]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
A bit too confusing to explain, but, when you change channels in a tab it doesn't update. When you swap to that tab it sometimes sends you to the channel it shows, not the last you've opened. 

**To Reproduce**
Open a new tab(it would be your friends list)
Switch to some channel in the newly opened tab.
Switch to a different tab and then back to your new one. You're back in your friends list.

**Expected behavior**
The tab header changes to whatever channel you switched to, and when you switch to that tab it stays on that channel.

**Screenshots**
![image](https://github.com/user-attachments/assets/85fdac47-a4d6-4e47-9756-03256b1c967f)
The right most tab is active. But it shows a different channel. When i swap from it and back, it returns me to the channel it shows on the top, not the latest channel i had open.

**Information (please complete the following information):**
 - OS: windows
 - Plugin Version: 2.6.13

 - Discord version:  stable 328697 (38204c9) Host 1.0.9163 x64 (52153) Build Override: N/A Windows 11 64-bit (10.0.22631)
 - Compact Mode enabled? no

**Comment by EnoralTheOutCast** [comment]
Update: I rebooted my client, and it stopped working completely.

**Comment by wstirl** [comment]
can confirm it doesn't work anymore

**Comment by Kamiikaze** [comment]
can confirm, too. Changing the location doesnt update the tab location. Switch to a new tab and than back, sends me back to an old location.

That's the error which came up when chaning the location in the tab

```
web.cde6776….js:12 [PluginManager] Unable to fire onSwitch for ChannelTabs v2.6.13

 TypeError: Cannot read properties of undefined (reading 'getIconURL')
    at getCurrentIconUrl (ChannelTabs.plugin.js:1306:20)
    at eval (ChannelTabs.plugin.js:3438:20)
    at Array.map (<anonymous>)
    at ChannelTabs.onSwitch (ChannelTabs.plugin.js:3430:43)
    at N.onSwitch (renderer.js:5:30384)
    at a.emit (renderer.js:5:368671)
    at a.dispatch (renderer.js:5:19988)
    at renderer.js:5:20161
    ```

**Comment by angsaysroar** [comment]
Can only upload/share their config files for those that deleted the plugin and reinstalled it?

**Comment by ZenMasta** [comment]
> For those who want to keep using the plugin till its update you can change Line 1304 From:
> 
> ```js
> return guild.getIconURL(40, false) || DefaultUserIconBlue;
> ```
> 
> To:
> 
> ```js
> return guild ? guild.getIconURL(40, false) : DefaultUserIconBlue;
> ```
> 
> So the icons will be default ones, but its useable again.

Sweet work around. I'll gladly give up server icons for functionality until this is officially patched.

**Comment by MegaShinySnivy** [comment]
@samfundev This is a critical break, any chance you can take a look at this?

**Comment by jack652** [comment]
same here
also can't open a favorite in a new tab by right clicking it

**Comment by JoshH265** [comment]
Also same issue, across all my devices which use the plugin

**Comment by danny8376** [comment]
More proper temp fix here:
Open ZeresPluginLibrary, go Line 381
change it from:
```js
    get GuildStore() {return _webpackmodules__WEBPACK_IMPORTED_MODULE_1__["default"].getByProps("getGuild", "getGuildIds");},
```
to:
```js
    get GuildStore() {return _webpackmodules__WEBPACK_IMPORTED_MODULE_1__["default"].getByProps("getGuild", "getGuildIds", "getRoles");},
```
should also fix multiple other plugins at the same time.

**Comment by AhmedSherif0904** [comment]
> More proper temp fix here: Open ZeresPluginLibrary, go Line 381 change it from:
> 
> ```js
>     get GuildStore() {return _webpackmodules__WEBPACK_IMPORTED_MODULE_1__["default"].getByProps("getGuild", "getGuildIds");},
> ```
> 
> to:
> 
> ```js
>     get GuildStore() {return _webpackmodules__WEBPACK_IMPORTED_MODULE_1__["default"].getByProps("getGuild", "getGuildIds", "getRoles");},
> ```
> 
> should also fix multiple other plugins at the same time.

this fixed other plugins for me but didnt fix channeltabs

**Comment by Phoenixlink1** [comment]
> More proper temp fix here: Open ZeresPluginLibrary, go Line 381 change it from:
> 
> ```js
>     get GuildStore() {return _webpackmodules__WEBPACK_IMPORTED_MODULE_1__["default"].getByProps("getGuild", "getGuildIds");},
> ```
> 
> to:
> 
> ```js
>     get GuildStore() {return _webpackmodules__WEBPACK_IMPORTED_MODULE_1__["default"].getByProps("getGuild", "getGuildIds", "getRoles");},
> ```
> 
> should also fix multiple other plugins at the same time.

This fixed it for me!

**Comment by Kamiikaze** [comment]
> More proper temp fix here: Open ZeresPluginLibrary, go Line 381 change it from:
> 
> ```js
>     get GuildStore() {return _webpackmodules__WEBPACK_IMPORTED_MODULE_1__["default"].getByProps("getGuild", "getGuildIds");},
> ```
> 
> to:
> 
> ```js
>     get GuildStore() {return _webpackmodules__WEBPACK_IMPORTED_MODULE_1__["default"].getByProps("getGuild", "getGuildIds", "getRoles");},
> ```
> 
> should also fix multiple other plugins at the same time.

Thanks, fixed it for me! :)

**Comment by samfundev** [comment]
The fix for this has been released in v2.6.14. It has not been approved yet, but feel free to [download the latest version](https://raw.githubusercontent.com/samfundev/BetterDiscordStuff/refs/heads/master/Plugins/ChannelTabs/ChannelTabs.plugin.js) in the mean time.

**Comment by doqfgc** [comment]
Fix did not work for me with just the 2.6.14 update; I also had to apply the Zeres Lib fix from https://github.com/samfundev/BetterDiscordStuff/issues/12#issuecomment-2395289463

**Comment by samfundev** [comment]
I believe this is fixed, please let me know if it's not!
